[package]
name = "CandyMachine"
version = "0.0.1"

[addresses]
candymachine = "0x999"

[dependencies]
AptosStdlib = { git="https://github.com/aptos-labs/aptos-core", rev="mainnet", subdir="aptos-move/framework/aptos-stdlib/" }
AptosToken = { git="https://github.com/aptos-labs/aptos-core", rev="mainnet", subdir="aptos-move/framework/aptos-token/" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="mainnet" }